/** @format */

const solve = require("../main");
const handleTest = require("d:/Programming/Solve_Puzzles/codin-game-problems/shared/testfuntion");
const object = {
    "name":  "06-Test-6",
    "input":  [
                  "40",
                  "XZADHVCOMBACBBHTEYCCXJDNNLMYYDVRQSAOWNOI",
                  "RZTKUWUMFVHBNEXKYVLQDRUFYAQKNIAIMJKBTGTA",
                  "EHAOTIYXUEVIQOXLMWTXJTXHNEZIBUQDRHGWTJOV",
                  "SMNHPIQCWIHIOHQBNMINYYUPKZWHSUFWKUMTENJA",
                  "VLFBINPJBIIXNHREZHUCUEIXMDOBMRMYYFIGTYEA",
                  "WRYSXJRQCGWOCBGQQORMTHLRYRQHACUUNRCHIRFV",
                  "JZBZWXKXMCTICXQALXZKHNXMTGPXXTQMMLHPEHGL",
                  "TTSURBLRCWGWSTVVELLVTCLJCRKTFSDBAOLGRHHN",
                  "OQLAKHARLJNJDIYHWSJRETNNZOVXEDOGNFJBPSXT",
                  "GZSTCXPBKPARDYSQGUUCKCSSPQAIKNVVFIXHWKUK",
                  "KJIAHTGEOGFBMTCQMZFCZGGTALBHOIZDOAEAVUKX",
                  "NABDPPDWUGXPMLOFHJBZJFNALQLXWNSPTCEOWDGD",
                  "ELAECPECRDVSKPUWUECZONMBZONPMZVFJQKCYHLC",
                  "XTFRWZHKFTZOCHDBVJZPPPHXYVBQEAWBOGEFXYIL",
                  "JIBXPJDKZPLTINBAOBUBZIUSISQPQZKUXZEGFHVV",
                  "BGVLWHNHYJNRMTQWWCLDGQVFNSHYDPRESKBWJMBN",
                  "SUFTWVUHUNNBXLBLVPHFNUADPBZIYOCMMJTOGBRU",
                  "VXUQTYNINPBJMLHPKFPDVCBYZCAKWASDPJEFYQPP",
                  "FUOSGBXGUZSODPITUAYOUFGCTYOBQCRCPFQMXFHY",
                  "JIHWAPIPQEKHFDULYPVKZVEOHWFZQJVKVIGIQRLI",
                  "DPIWHKRZVKYOEINTAVFMPBXLVYMGDHCSZIQPELHM",
                  "CJTVHFCMJBOGXWYWAHWXRASNTJFTAXCSJOELOYIN",
                  "ARCQUIJKAJIPLKQNFTYQZFMMHADTCBPRQQUVJXOV",
                  "OEUOOYJNXOUNFZWOOSOYCDISWAMEVFYZFTDCFDFG",
                  "OTQRWRPTUSIKRRYKJVEYGSXQSEGNNPQPVKJJDWDU",
                  "RBIIAEUNUCRKWZWNRLCBRVBFIOWWDBXLWTMBGFIW",
                  "UWYVUNGLTPOAUIVZTFDNAVGPZWSVOIZGBDXNFWKF",
                  "PRNRBRKQTKZPZRPXTJXZCACJFAKTGOVOWRXIQIEY",
                  "ZEJHECJGTJYSAVCBXLKUCDVIGQQGRXNSCOFZSRZJ",
                  "RVUJLHKDVNTYXCWGKPPSIWWTSOJXUYVAEVIFOXKH",
                  "PGLLUAICYQRASURUOGTJNKHAXJLNOGOKXQHQYKRS",
                  "NSVKBFGQFQHPCPUENNCPNWEEJUGUMVFUVXXFMQBA",
                  "KTXYSCTFRGDRRFTKRQFDQTLFNFWRDOMVTQLRLIOX",
                  "BQMCCWRYMHCAMSSRGRPCEPZTYIWAMYQCHSBCAKIM",
                  "LTURGHLZQJZSTFXPPVBHZKKNAMTYPHCVEBFKBABY",
                  "JGYXBZRDJEYUCGFYYZLZXBLUKFHMAJYIDKKWFKRE",
                  "XLLTZANFRHDLEGTCSHWEJYNXNVGXJAJMXPJNVGSB",
                  "WJQQOLKPVIYUFFEMFOJHTJCWASTILFGGHWUECWAJ",
                  "HIQTTIUXRSIKZIBXVKMXEKQKBUGFUMEZGZXCBKQE",
                  "DEHPKLWEXHGMYRYZTGHUAQVIHUZKRTVTARLKCVBN"
              ],
    "output":  [
                   "4832"
               ]
};
const readline = () => {
	return object.input.shift();
};
// Mocking user input and capturing console.log output
test(object.name, () => handleTest(object.output, solve, readline));

